name: ci
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The next release tag to use'
        required: false
        type: string
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
env:
  # Use docker.io for Docker Hub if empty 
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          install: true
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.tag }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm/v7,linux/arm64/v8,linux/arm/v6,linux/amd64
          push: true
          tags: ozbillwang/demo:latest
